version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: postgres-vectores
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: productos
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: redis-broker
    ports:
      - "6379:6379"
    restart: unless-stopped

  web:
    build: .
    container_name: fastapi-app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_HOST=host.docker.internal
      - DATABASE_PORT=5432
      - DATABASE_NAME=productos
      - DATABASE_USER=admin
      - DATABASE_PASSWORD=admin123
      - REDIS_HOST=host.docker.internal
      - REDIS_URL=redis://host.docker.internal:6379/0
      - OPENAI_API_KEY=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
      - OPENAI_BASE_URL=https://integrate.api.nvidia.com/v1
      - OPENAI_MODEL=deepseek-ai/deepseek-v4-flash
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

  worker:
    build: .
    container_name: celery-worker
    command: celery -A celery_app.celery_app worker --loglevel=info
    environment:
      - DATABASE_HOST=host.docker.internal
      - DATABASE_PORT=5432
      - DATABASE_NAME=productos
      - DATABASE_USER=admin
      - DATABASE_PASSWORD=admin123
      - REDIS_HOST=host.docker.internal
      - REDIS_URL=redis://host.docker.internal:6379/0
      - OPENAI_API_KEY=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
      - OPENAI_BASE_URL=https://integrate.api.nvidia.com/v1
      - OPENAI_MODEL=deepseek-ai/deepseek-v4-flash
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

volumes:
  postgres_data: