version: '3.8'

services:
  web:
    build: .
    container_name: fastapi-app
    ports:
      - "8000"
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - shared-images:/app/images

  worker:
    build: .
    container_name: celery-worker
    command: celery -A celery_app.celery_app worker --loglevel=info
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - shared-images:/app/images

volumes:
  shared-images: