version: '3.8'

services:
  web:
    build: .
    container_name: fastapi-app
    ports:
      - "8000"
    environment:
      - DATABASE_HOST=161.132.49.206
      - DATABASE_PORT=5432
      - DATABASE_NAME=productos
      - DATABASE_USER=admin
      - DATABASE_PASSWORD=admin123
      - REDIS_HOST=161.132.49.206
      - REDIS_PORT=6379
      - REDIS_DB=0
      - REDIS_USER=default
      - REDIS_PASSWORD=123
      - OPENAI_API_KEY=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
      - OPENAI_BASE_URL=https://integrate.api.nvidia.com/v1
      - OPENAI_MODEL=deepseek-ai/deepseek-v4-flash
      - TORCH_ONEDNN_OPTS=0
    restart: unless-stopped
    volumes:
      - shared-images:/app/images

  worker:
    build: .
    container_name: celery-worker
    command: celery -A celery_app.celery_app worker --loglevel=info
    environment:
      - DATABASE_HOST=161.132.49.206
      - DATABASE_PORT=5432
      - DATABASE_NAME=productos
      - DATABASE_USER=admin
      - DATABASE_PASSWORD=admin123
      - REDIS_HOST=161.132.49.206
      - REDIS_PORT=6379
      - REDIS_DB=0
      - REDIS_USER=default
      - REDIS_PASSWORD=123
      - OPENAI_API_KEY=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
      - OPENAI_BASE_URL=https://integrate.api.nvidia.com/v1
      - OPENAI_MODEL=deepseek-ai/deepseek-v4-flash
      - TORCH_ONEDNN_OPTS=0
    restart: unless-stopped
    volumes:
      - shared-images:/app/images

volumes:
  shared-images: